version: 0.2
language: en
words:
    - HomeWizard # Brand
    - Vacatures # Foreign
    - Noordwijk # Foreign
    - Watermeter
    - montly # Known typo
    - hwenergy
    - energysocket
    - watermeter
    - kwhmeter
    - Zeroconf # Name
    - DSMR # Name
    - capaciteitstarief # Foreign
    - ISKRA # Name
    - AABBCC # Example
    - AABBCCDDEEFF # Example
    - DDEEFF # Example
    - YYMMDDhhmmss # Example
    - rssi # Known acronym
