---
repos:
    - repo: local
      hooks:
          - id: linter
            name: Linter
            pass_filenames: False
            language: system
            entry: npm run lint

          - id: formatter
            name: Formatter
            pass_filenames: False
            language: system
            entry: npm run format

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: no-commit-to-branch
            name: Check if commit is not in branch 'main'
            args:
                - --branch=main

          - id: end-of-file-fixer
          - id: check-json
          - id: check-yaml
          - id: check-added-large-files
          - id: check-case-conflict
          - id: trailing-whitespace
          - id: mixed-line-ending
