blank_issues_enabled: false
contact_links:
    - name: Propose a feature request
      url: https://helpdesk.homewizard.com
      about: This is the issue tracker for our API documentation. Please pitch your feature requests via HomeWizard Support.
